import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { getActiveStudent } from '@/lib/student';
import { masteryLevel } from '@/lib/bkt';

export const dynamic = 'force-dynamic';

/**
 * GET /api/parent/report — the parent's weekly view.
 *
 * TRUST GATE: every number here is computed from persisted QuestionAttempt
 * and ConceptMastery rows — no LLM anywhere in this route, so the report can
 * never say something the data doesn't. Language is plain English for
 * parents, generated by template, and each headline links back to the data
 * that produced it.
 */
export async function GET(_req: NextRequest) {
  try {
    const student = await getActiveStudent();
    const weekAgo = new Date(Date.now() - 7 * 86_400_000);

    const [attempts, masteries] = await Promise.all([
      prisma.questionAttempt.findMany({
        where: { studentId: student.id, createdAt: { gte: weekAgo } },
        include: {
          question: {
            select: {
              type: true,
              marks: true,
              chapter: {
                select: {
                  id: true,
                  number: true,
                  title: true,
                  subject: { select: { name: true, grade: { select: { number: true } } } },
                },
              },
            },
          },
        },
        orderBy: { createdAt: 'asc' },
      }),
      prisma.conceptMastery.findMany({ where: { studentId: student.id } }),
    ]);

    // ── Per-chapter aggregation of this week's work ──
    const byChapter = new Map<
      string,
      {
        chapter: string;
        subject: string;
        grade: number;
        attempts: number;
        earned: number;
        possible: number;
        days: Set<string>;
      }
    >();
    for (const a of attempts) {
      const ch = a.question.chapter;
      const key = ch.id;
      const row = byChapter.get(key) ?? {
        chapter: `Chapter ${ch.number}: ${ch.title}`,
        subject: ch.subject.name,
        grade: ch.subject.grade.number,
        attempts: 0,
        earned: 0,
        possible: 0,
        days: new Set<string>(),
      };
      row.attempts += 1;
      row.earned += a.scoreAwarded;
      row.possible += a.maxMarks;
      row.days.add(a.createdAt.toISOString().slice(0, 10));
      byChapter.set(key, row);
    }

    const chapters = Array.from(byChapter.values()).map((c) => ({
      chapter: c.chapter,
      subject: c.subject,
      grade: c.grade,
      questionsAttempted: c.attempts,
      score: `${Math.round(c.earned * 10) / 10} out of ${c.possible} marks`,
      percentage: c.possible > 0 ? Math.round((c.earned / c.possible) * 100) : 0,
      activeDays: c.days.size,
    }));

    // ── Mastery snapshot (chapter-level keys only, for readability) ──
    const chapterMasteries = masteries.filter((m) => /\.(?:[a-z0-9-]+-)?ch-\d+$/.test(m.conceptKey));
    const mastered = chapterMasteries.filter((m) => masteryLevel(m.pKnown) === 'mastered');
    const developing = chapterMasteries.filter((m) => masteryLevel(m.pKnown) === 'developing');
    const needsWork = chapterMasteries.filter((m) => masteryLevel(m.pKnown) === 'needs_work');

    const activeDays = new Set(attempts.map((a) => a.createdAt.toISOString().slice(0, 10))).size;
    const totalEarned = attempts.reduce((s, a) => s + a.scoreAwarded, 0);
    const totalPossible = attempts.reduce((s, a) => s + a.maxMarks, 0);

    // Plain-language headlines — pure templates over the numbers above.
    const headlines: string[] = [];
    if (attempts.length === 0) {
      headlines.push('No practice was recorded this week. A 10-minute session on any chapter is a good restart.');
    } else {
      headlines.push(
        `${student.name} practised on ${activeDays} day${activeDays === 1 ? '' : 's'} this week, answering ${attempts.length} question${attempts.length === 1 ? '' : 's'} and earning ${Math.round(totalEarned * 10) / 10} of ${totalPossible} marks (${totalPossible > 0 ? Math.round((totalEarned / totalPossible) * 100) : 0}%).`
      );
      const best = [...chapters].sort((a, b) => b.percentage - a.percentage)[0];
      if (best && best.percentage >= 70) {
        headlines.push(`Strongest work: ${best.subject}, ${best.chapter} — ${best.score}.`);
      }
      const weakest = [...chapters].sort((a, b) => a.percentage - b.percentage)[0];
      if (weakest && weakest.percentage < 50 && chapters.length > 1) {
        headlines.push(
          `Needs a second look: ${weakest.subject}, ${weakest.chapter} — ${weakest.score}. A short revision of this chapter would help most.`
        );
      }
    }
    if (needsWork.length > 0) {
      headlines.push(
        `${needsWork.length} topic${needsWork.length === 1 ? ' is' : 's are'} below the 60% understanding mark and scheduled for extra practice.`
      );
    }
    if (mastered.length > 0) {
      headlines.push(
        `${mastered.length} topic${mastered.length === 1 ? ' now counts' : 's now count'} as mastered (95%+ understanding).`
      );
    }

    return NextResponse.json({
      student: { name: student.name, grade: student.grade },
      period: { from: weekAgo.toISOString().slice(0, 10), to: new Date().toISOString().slice(0, 10) },
      headlines,
      week: {
        activeDays,
        questionsAttempted: attempts.length,
        marksEarned: Math.round(totalEarned * 10) / 10,
        marksPossible: totalPossible,
        chapters,
      },
      understanding: {
        mastered: mastered.length,
        developing: developing.length,
        needsWork: needsWork.length,
        note: 'Understanding percentages come from Bayesian Knowledge Tracing over every answer — the same numbers the student sees.',
      },
      dataNote:
        'Everything in this report is computed directly from recorded answers. No content is AI-generated.',
    });
  } catch (error) {
    console.error('parent report error:', error);
    return NextResponse.json({ error: 'Failed to build report' }, { status: 500 });
  }
}
